name: "Setup Python and Poetry"
description: "Setup Python environment with Poetry"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install poetry
      shell: bash
      run: |
        python -m pip install poetry
    - name: Install dependencies
      shell: bash
      run: |
        poetry install --no-interaction --no-root
