name: Push

on:
  schedule:
    - cron: "0 20 * * *" # UTC 20:00 = KST 05:00
  workflow_dispatch:

jobs:
  check-attendance:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run attendance checks
        run: |
          echo "::group::Book Read Check"
          poetry run python push.py 책읽어또
          echo "::endgroup::"

          echo "::group::Garlic Check"
          poetry run python push.py 다진마늘
          echo "::endgroup::"
        env:
          SHEETS_ID: ${{ secrets.SHEETS_ID }}
          GEULTTO_SLACK_TOKEN: ${{ secrets.GEULTTO_SLACK_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
          MINCED_GARLIC_CHANNEL_ID: ${{ vars.MINCED_GARLIC_CHANNEL_ID }}
          BOOK_READ_CHANNEL_ID: ${{ vars.BOOK_READ_CHANNEL_ID }}
